//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telerik.Web.Mvc.Resources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; array cannot be empty..
        /// </summary>
        internal static string ArrayCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArrayCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative..
        /// </summary>
        internal static string CannotBeNegative {
            get {
                return ResourceManager.GetString("CannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative or zero..
        /// </summary>
        internal static string CannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("CannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be null..
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be null or empty..
        /// </summary>
        internal static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a public property of primitive type to sort by..
        /// </summary>
        internal static string CannotFindPropertyToSortBy {
            get {
                return ResourceManager.GetString("CannotFindPropertyToSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more one column in order when sort mode is set to single column..
        /// </summary>
        internal static string CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn {
            get {
                return ResourceManager.GetString("CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot route to class named &apos;Controller&apos;..
        /// </summary>
        internal static string CannotRouteToClassNamedController {
            get {
                return ResourceManager.GetString("CannotRouteToClassNamedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use Ajax and WebService binding at the same time..
        /// </summary>
        internal static string CannotUseAjaxAndWebServiceAtTheSameTime {
            get {
                return ResourceManager.GetString("CannotUseAjaxAndWebServiceAtTheSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use only server templates in Ajax or WebService binding mode. Please specify a client template as well..
        /// </summary>
        internal static string CannotUseTemplatesInAjaxOrWebService {
            get {
                return ResourceManager.GetString("CannotUseTemplatesInAjaxOrWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; collection cannot be empty..
        /// </summary>
        internal static string CollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{1}.
        /// </summary>
        internal static string ControllerNameAmbiguousWithoutRouteUrl {
            get {
                return ResourceManager.GetString("ControllerNameAmbiguousWithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{2}.
        /// </summary>
        internal static string ControllerNameAmbiguousWithRouteUrl {
            get {
                return ResourceManager.GetString("ControllerNameAmbiguousWithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller name must end with &apos;Controller&apos;..
        /// </summary>
        internal static string ControllerNameMustEndWithController {
            get {
                return ResourceManager.GetString("ControllerNameMustEndWithController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataKeys collection is empty. Please specify a data key..
        /// </summary>
        internal static string DataKeysEmpty {
            get {
                return ResourceManager.GetString("DataKeysEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date should be bigger than MinDate and less than MaxDate..
        /// </summary>
        internal static string DateOutOfRange {
            get {
                return ResourceManager.GetString("DateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete data binding setting is required by the delete command. Please specify the Delete action or url in the DataBinding configuration..
        /// </summary>
        internal static string DeleteCommandRequiresDelete {
            get {
                return ResourceManager.GetString("DeleteCommandRequiresDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update data binding setting is required by the edit command. Please specify the Update action or url in the DataBinding configuration..
        /// </summary>
        internal static string EditCommandRequiresUpdate {
            get {
                return ResourceManager.GetString("EditCommandRequiresUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with specified name already exists..
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExists {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with specified name &quot;{0}&quot; already exists. Please specify a different name..
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with &quot;{0}&quot; does not exist in {1} SharedWebAssets..
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with specified name &quot;{0}&quot; does not exist. Please make sure you have specified a correct name..
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided index is out of range..
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert data binding setting is required by the insert command. Please specify the Insert action or url in the DataBinding configuration..
        /// </summary>
        internal static string InsertCommandRequiresInsert {
            get {
                return ResourceManager.GetString("InsertCommandRequiresInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with specified source already exists..
        /// </summary>
        internal static string ItemWithSpecifiedSourceAlreadyExists {
            get {
                return ResourceManager.GetString("ItemWithSpecifiedSourceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local group with name &quot;{0}&quot; already exists..
        /// </summary>
        internal static string LocalGroupWithSpecifiedNameAlreadyExists {
            get {
                return ResourceManager.GetString("LocalGroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound columns require a field or property access expression..
        /// </summary>
        internal static string MemberExpressionRequired {
            get {
                return ResourceManager.GetString("MemberExpressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinDate should be less than MaxDate..
        /// </summary>
        internal static string MinDateShouldBeLessThanMaxDate {
            get {
                return ResourceManager.GetString("MinDateShouldBeLessThanMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinHeight should be less than MaxHeight..
        /// </summary>
        internal static string MinHeightShouldBeLessThanMaxHeight {
            get {
                return ResourceManager.GetString("MinHeightShouldBeLessThanMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinValue should be less than MaxValue.
        /// </summary>
        internal static string MinValueShouldBeLessThanMaxValue {
            get {
                return ResourceManager.GetString("MinValueShouldBeLessThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinWidth should be less than MaxWidth..
        /// </summary>
        internal static string MinWidthShouldBeLessThanMaxWidth {
            get {
                return ResourceManager.GetString("MinWidthShouldBeLessThanMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be blank..
        /// </summary>
        internal static string NameCannotBeBlank {
            get {
                return ResourceManager.GetString("NameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;None&quot; is only used for internal purpose..
        /// </summary>
        internal static string NoneIsOnlyUsedForInternalPurpose {
            get {
                return ResourceManager.GetString("NoneIsOnlyUsedForInternalPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one ScriptRegistrar is allowed in a single request..
        /// </summary>
        internal static string OnlyOneScriptRegistrarIsAllowedInASingleRequest {
            get {
                return ResourceManager.GetString("OnlyOneScriptRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one StyleSheetRegistrar is allowed in a single request..
        /// </summary>
        internal static string OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest {
            get {
                return ResourceManager.GetString("OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only property and field expressions are supported.
        /// </summary>
        internal static string OnlyPropertyAndFieldExpressionsAreSupported {
            get {
                return ResourceManager.GetString("OnlyPropertyAndFieldExpressionsAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be bigger than {1} and less then {2}.
        /// </summary>
        internal static string PropertyShouldBeInRange {
            get {
                return ResourceManager.GetString("PropertyShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have SiteMap defined with key &quot;{0}&quot; in ViewData dictionary..
        /// </summary>
        internal static string SiteMapShouldBeDefinedInViewData {
            get {
                return ResourceManager.GetString("SiteMapShouldBeDefinedInViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source must be a virtual path which should starts with &quot;~/&quot;.
        /// </summary>
        internal static string SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash {
            get {
                return ResourceManager.GetString("SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file does not exist: &quot;{0}&quot;..
        /// </summary>
        internal static string SpecifiedFileDoesNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed string cannot be parsed to DateTime object..
        /// </summary>
        internal static string StringNotCorrectDate {
            get {
                return ResourceManager.GetString("StringNotCorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method is not an action method..
        /// </summary>
        internal static string TheSpecifiedMethodIsNotAnActionMethod {
            get {
                return ResourceManager.GetString("TheSpecifiedMethodIsNotAnActionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set Url and ContentUrl at the same time..
        /// </summary>
        internal static string UrlAndContentUrlCannotBeSet {
            get {
                return ResourceManager.GetString("UrlAndContentUrlCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be bigger than MinValue and less than MaxValue..
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url of the WebService must be set.
        /// </summary>
        internal static string WebServiceUrlRequired {
            get {
                return ResourceManager.GetString("WebServiceUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than once column when sort mode is set to single column..
        /// </summary>
        internal static string YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle {
            get {
                return ResourceManager.GetString("YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot call render more than once..
        /// </summary>
        internal static string YouCannotCallRenderMoreThanOnce {
            get {
                return ResourceManager.GetString("YouCannotCallRenderMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot call Start more than once..
        /// </summary>
        internal static string YouCannotCallStartMoreThanOnce {
            get {
                return ResourceManager.GetString("YouCannotCallStartMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot configure a shared web asset group..
        /// </summary>
        internal static string YouCannotConfigureASharedWebAssetGroup {
            get {
                return ResourceManager.GetString("YouCannotConfigureASharedWebAssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have to call Start prior calling this method..
        /// </summary>
        internal static string YouMustHaveToCallStartPriorCallingThisMethod {
            get {
                return ResourceManager.GetString("YouMustHaveToCallStartPriorCallingThisMethod", resourceCulture);
            }
        }
    }
}
